import { UserButton } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import { Input } from "@/components/ui/input";
import { HomeHeader } from "../features/home/components";

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Course Explorer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center  bg-gradient-to-b from-[#03045E] to-[#023E8A] p-4">
        <div className="w-full max-w-lg space-y-4 rounded-md bg-white p-4">
          <HomeHeader />
          <Input placeholder="Search any course you like..." type="text" />

          <h4>Courses you might like:</h4>
        </div>
      </main>
    </>
  );
};

export default HomePage;
